### PR TITLE
Correct input buffer for the resampler

### LINKED ISSUE #91: Assertion failed on `test_destroy_duplex_stream_after_unplugging_a_nondefault_input_device`
Here is the assertion failed:
<pre>
cchang@cchang-37365 cubeb-coreaudio-rs % cargo test test_destroy_duplex_stream_after_unplugging_a_nondefault_input_device -- --ignored --nocapture 
    Finished test [unoptimized + debuginfo] target(s) in 0.03s
     Running target/debug/deps/cubeb_coreaudio-ebf01d779bba143b

running 1 test
Assertion failed: (destination && source), function PodCopy, file /Users/cchang/.cargo/registry/src/github.com-1ecc6299db9ec823/cubeb-sys-0.7.0/libcubeb/src/cubeb_utils.h, line 31.
error: test failed, to rerun pass '--lib'

Caused by:
  process didn't exit successfully: `/Users/cchang/Work/cubeb-coreaudio-rs/target/debug/deps/cubeb_coreaudio-ebf01d779bba143b test_destroy_duplex_stream_after_unplugging_a_nondefault_input_device --ignored --nocapture` (signal: 6, SIGABRT: process abort signal)
</pre>

Here is the *backtrace* in `lldb`:
<pre>
cchang@cchang-37365 cubeb-coreaudio-rs % lldb target/debug/deps/cubeb_coreaudio-ebf01d779bba143b 
(lldb) target create "target/debug/deps/cubeb_coreaudio-ebf01d779bba143b"
Current executable set to 'target/debug/deps/cubeb_coreaudio-ebf01d779bba143b' (x86_64).
(lldb) r test_destroy_duplex_stream_after_unplugging_a_nondefault_input_device --ignored --nocapture
Process 4354 launched: '/Users/cchang/Work/cubeb-coreaudio-rs/target/debug/deps/cubeb_coreaudio-ebf01d779bba143b' (x86_64)

running 1 test
2020-05-06 10:31:42.061895-0700 cubeb_coreaudio-ebf01d779bba143b[4354:69748] [plugin] AddInstanceForFactory: No factory registered for id <CFUUID 0x1013083a0> F8BB1C28-BAE8-11D6-9C31-00039315CD46
2020-05-06 10:31:42.101003-0700 cubeb_coreaudio-ebf01d779bba143b[4354:69748]  HALC_ShellDriverPlugIn::Open: Can't get a pointer to the Open routine
2020-05-06 10:31:42.101657-0700 cubeb_coreaudio-ebf01d779bba143b[4354:69748]  HALC_ShellDriverPlugIn::Open: Can't get a pointer to the Open routine
2020-05-06 10:31:42.108476-0700 cubeb_coreaudio-ebf01d779bba143b[4354:69748]  HALC_ShellDriverPlugIn::Open: Can't get a pointer to the Open routine
Assertion failed: (destination && source), function PodCopy, file /Users/cchang/.cargo/registry/src/github.com-1ecc6299db9ec823/cubeb-sys-0.7.0/libcubeb/src/cubeb_utils.h, line 31.
Process 4354 stopped
* thread #8, name = 'com.apple.audio.IOThread.client', stop reason = signal SIGABRT
    frame #0: 0x00007fff6d7ce33a libsystem_kernel.dylib`__pthread_kill + 10
libsystem_kernel.dylib`__pthread_kill:
->  0x7fff6d7ce33a <+10>: jae    0x7fff6d7ce344            ; <+20>
    0x7fff6d7ce33c <+12>: movq   %rax, %rdi
    0x7fff6d7ce33f <+15>: jmp    0x7fff6d7c8629            ; cerror_nocancel
    0x7fff6d7ce344 <+20>: retq   
Target 0: (cubeb_coreaudio-ebf01d779bba143b) stopped.
(lldb) bt
* thread #8, name = 'com.apple.audio.IOThread.client', stop reason = signal SIGABRT
  * frame #0: 0x00007fff6d7ce33a libsystem_kernel.dylib`__pthread_kill + 10
    frame #1: 0x00007fff6d88ae60 libsystem_pthread.dylib`pthread_kill + 430
    frame #2: 0x00007fff6d755808 libsystem_c.dylib`abort + 120
    frame #3: 0x00007fff6d754ac6 libsystem_c.dylib`__assert_rtn + 314
    frame #4: 0x00000001001b1722 cubeb_coreaudio-ebf01d779bba143b`void PodCopy<float>(destination=0x0000000000000000, source=0x0000000102037c00, count=0) at cubeb_utils.h:31:3
    frame #5: 0x00000001001af60a cubeb_coreaudio-ebf01d779bba143b`auto_array<float>::push(this=0x000000010101f030, elements=0x0000000102037c00, length=0) at cubeb_utils.h:198:5
    frame #6: 0x00000001001b6e4e cubeb_coreaudio-ebf01d779bba143b`cubeb_resampler_speex_one_way<float>::input(this=0x000000010101f010, input_buffer=0x0000000102037c00, input_frame_count=0) at cubeb_resampler_internal.h:216:26
    frame #7: 0x00000001001b63ea cubeb_coreaudio-ebf01d779bba143b`cubeb_resampler_speex<float, cubeb_resampler_speex_one_way<float>, cubeb_resampler_speex_one_way<float> >::fill_internal_duplex(this=0x000000010101a520, in_buffer=0x0000000102037c00, input_frames_count=0x0000700007eb4800, out_buffer=0x00000001012cf010, output_frames_needed=512) at cubeb_resampler.cpp:288:22
    frame #8: 0x00000001001b6922 cubeb_coreaudio-ebf01d779bba143b`cubeb_resampler_speex<float, cubeb_resampler_speex_one_way<float>, cubeb_resampler_speex_one_way<float> >::fill(this=0x000000010101a520, input_buffer=0x0000000102037c00, input_frames_count=0x0000700007eb4800, output_buffer=0x00000001012cf010, output_frames_needed=512) at cubeb_resampler.cpp:174:10
    frame #9: 0x00000001001b12d0 cubeb_coreaudio-ebf01d779bba143b`::cubeb_resampler_fill(resampler=0x000000010101a520, input_buffer=0x0000000102037c00, input_frames_count=0x0000700007eb4800, output_buffer=0x00000001012cf010, output_frames_needed=512) at cubeb_resampler.cpp:374:21
    frame #10: 0x00000001000bbffe cubeb_coreaudio-ebf01d779bba143b`cubeb_coreaudio::backend::resampler::Resampler::fill::h225081ff4af4ef3a(self=0x000000010131cf58, input_buffer=0x0000000102037c00, input_frame_count=0x0000700007eb4800, output_buffer=0x00000001012cf010, output_frames_needed=512) at resampler.rs:52:13
    frame #11: 0x00000001000c1729 cubeb_coreaudio-ebf01d779bba143b`cubeb_coreaudio::backend::audiounit_output_callback::_$u7b$$u7b$closure$u7d$$u7d$::h6f3331137d437f07((null)=0x0000700007eb6940, stm=0x000000010131ce50, output_frames=512, buffers=&mut [coreaudio_sys::AudioBuffer] @ 0x0000700007eb5528) at mod.rs:657:25
    frame #12: 0x00000001000d9060 cubeb_coreaudio-ebf01d779bba143b`cubeb_coreaudio::backend::audiounit_output_callback::hdd2ba8278e53a428(user_ptr=0x000000010131ce50, (null)=0x0000700007eb6d00, tstamp=0x0000700007eb6c88, bus=0, output_frames=512, out_buffer_list=0x0000000101020820) at mod.rs:718:34
    frame #13: 0x0000000101509d98 CoreAudio`___lldb_unnamed_symbol90$$CoreAudio + 966
    frame #14: 0x000000010152bc23 CoreAudio`___lldb_unnamed_symbol675$$CoreAudio + 1473
    frame #15: 0x000000010150cdf5 CoreAudio`___lldb_unnamed_symbol175$$CoreAudio + 2001
    frame #16: 0x00007fff32d25aaa CoreAudio`___ZN19HALC_ProxyIOContextC2Ejj_block_invoke + 5639
    frame #17: 0x00007fff32e58c22 CoreAudio`HALB_IOThread::Entry(void*) + 72
    frame #18: 0x00007fff6d88b109 libsystem_pthread.dylib`_pthread_start + 148
    frame #19: 0x00007fff6d886b8b libsystem_pthread.dylib`thread_start + 15
(lldb) 
</pre>

### PR DESCRIPTION
**Pull request by ChunMinChang**
The change here fixes #91 and complete what we want to do in #86.

The `assert(destination && source)` in [1] will be hit in the following
scenario:

1. `audiounit_output_callback` comes before `audiounit_input_callback`
2. `audiounit_input_callback` is never called before 1
3. `input_buffer_manager.available_samples()` is `0` since no buffered
   input data
4. the `input_frame_count` of the *first* `ffi::cubeb_resampler_fill`
   would be `0`

The *silent frames* needs to be fed as the input buffer to the
resampler.

[1] https://github.com/kinetiknz/cubeb/blob/35190a8da650be297edb91d2db778bed622d8691/src/cubeb_utils.h#L31

### CODE REVIEW

**Comment by padenot** [comment]
Won't this reintroduce the problems of https://github.com/ChunMinChang/cubeb-coreaudio-rs/pull/79 ?

File: src/backend/mod.rs [hunk 1]
```diff
@@ -643,12 +643,15 @@ extern "C" fn audiounit_output_callback(
                     },
                     silent_frames_to_push
                 );
-            }
+                input_frames_needed
```
Comment (ChunMinChang) [inline src/backend/mod.rs:646]: This is a bit safer approach. We only push *silent frames* when the following `if` condition is met:
https://github.com/ChunMinChang/cubeb-coreaudio-rs/blob/c5aacdc75618025e72f62f727a7a0d91606e6276/src/backend/mod.rs#L627-L631

Therefore, for most of the time, `buffered_input_frames` is used to be the input-frames for the resampler.

In addition, it fits the intention of the comment below:
> // The silent frames will be inserted in `get_linear_data` below.

**Comment by ChunMinChang** [comment]
> Won't this reintroduce the problems of #79 ?

I am unable to reproduce the glitch that #79 tried to fix. It's better to create a regression test to prevent that glitch otherwise that problem might popup again.

However, from the code we used to have in #79, the *silent frames* would be appended to the `buffer_manager` in the following case:
https://github.com/ChunMinChang/cubeb-coreaudio-rs/blob/27cf89ef920d1968c06e45f2a7903725d6b635cd/src/backend/mod.rs#L609-L615
and then the corrected buffer (with newly added *silent frames*) would be fed to the resampler:
https://github.com/ChunMinChang/cubeb-coreaudio-rs/blob/27cf89ef920d1968c06e45f2a7903725d6b635cd/src/backend/mod.rs#L631-L635

This is same as what the current change does here. The difference is that this patch would append the *silent frames* by `get_linear_data` implicitly instead of calling `push_silent_data` and then using `get_linear_data` (`push_silent_data` is removed). Thus, if the fix in #79 doesn't cause the glitch, the change here won't cause the glitch as well (however I am not able to test the glitch).

**Comment by ChunMinChang** [comment]
https://github.com/ChunMinChang/cubeb-coreaudio-rs/issues/91#issuecomment-625489253: Another approach is allowing push `0` frames to the resampler once it's initialized.

File: src/backend/mod.rs [hunk 2]
```diff
@@ -643,12 +643,15 @@ extern "C" fn audiounit_output_callback(
...
+            } else {
+                buffered_input_frames
+            };
 
-            let input_samples_needed = buffered_input_frames * input_channels;
+            let input_samples_needed = input_buffer_frames * input_channels;
```
Comment (padenot) [inline src/backend/mod.rs]: `s/input_buffer_frames/input_frames/` (they might not be buffered).

**Review by padenot — APPROVED** [review]
